

const ALERT = 'ALERT';
const REFETCH_CHATS = 'REFETCH_CHATS';
const NEW_ATTACHMENT = 'NEW_ATTACHMENT';
const NEW_MESSAGE = 'NEW_MESSAGE';

const NEW_REQUEST = 'NEW_REQUEST';

const NEW_MESSAGE_USER = 'NEW_MESSAGE_USER';



export { ALERT, REFETCH_CHATS, NEW_ATTACHMENT, NEW_MESSAGE, NEW_REQUEST, NEW_MESSAGE_USER }