

const ALERT = 'ALERT';
const REFETCH_CHATS = 'REFETCH_CHATS';
const NEW_ATTACHMENT = 'NEW_ATTACHMENT';
const NEW_MESSAGE = 'NEW_MESSAGE';



export { ALERT, REFETCH_CHATS, NEW_ATTACHMENT, NEW_MESSAGE }